---
include:
  - project: 'core/ci-config'
    ref: master
    file: 'config/common/master.yml'
  - project: 'core/ci-config'
    ref: master
    file: 'jobs/common/master.yml'

before_script:
  - . /duneci/bin/duneci-init-job
  - duneci-install-module https://gitlab.dune-project.org/core/dune-common.git
  - duneci-install-module https://gitlab.dune-project.org/core/dune-geometry.git
  - duneci-install-module https://gitlab.dune-project.org/staging/dune-uggrid.git

variables:
  # Alberta + python bindings fail at the moment with linker error
  DUNECI_CMAKE_FLAGS: '-DCMAKE_DISABLE_FIND_PACKAGE_Alberta=TRUE'

debian-11-gcc-9-17-nobindings:
  image: registry.dune-project.org/docker/ci/debian:11
  script: duneci-standard-test
  stage: test
  variables:
    DUNECI_TOOLCHAIN:  gcc-9-17
    DUNECI_CMAKE_FLAGS: '-DDUNE_ENABLE_PYTHONBINDINGS=OFF'
  tags: [duneci]
ubuntu-20.04-clang-10-20-nopython:
  image: registry.dune-project.org/docker/ci/ubuntu:20.04
  script: duneci-standard-test
  stage: test
  variables:
    DUNECI_TOOLCHAIN: clang-10-20
    DUNECI_CMAKE_FLAGS: '-DCMAKE_DISABLE_FIND_PACKAGE_Python3=TRUE'
  tags: [duneci]

# no numpy version available for this image on the gitlab registry
# disable python bindings for now
ubuntu:18.04 clang-6-17:
  image: registry.dune-project.org/docker/ci/ubuntu:18.04
  script: duneci-standard-test
  stage: test
  variables:
    DUNECI_TOOLCHAIN: clang-6-17
    DUNECI_CMAKE_FLAGS: "-DDUNE_ENABLE_PYTHONBINDINGS=OFF"
  tags: [duneci]
ubuntu:18.04 clang-5-17:
  image: registry.dune-project.org/docker/ci/ubuntu:18.04
  script: duneci-standard-test
  stage: test
  variables:
    DUNECI_TOOLCHAIN: clang-5-17
    DUNECI_CMAKE_FLAGS: "-DDUNE_ENABLE_PYTHONBINDINGS=OFF"
  tags: [duneci]

debian-10-clang-7-17-werror:
  image: registry.dune-project.org/docker/ci/debian:10
  script: duneci-standard-test
  variables:
    DUNECI_TOOLCHAIN:   clang-7-libcpp-17
    DUNE_CMAKE_FLAGS:   "-DCMAKE_CXX_FLAGS='-std=c++17 -O2 -g -Wall -Werror -Wno-unused-function -Wno-unneeded-internal-declaration -Wno-deprecated-declarations -Wno-unknown-warning-option -Wno-tautological-constant-out-of-range-compare -Wno-unused-variable -fdiagnostics-color=always' -DDUNE_MAX_TEST_CORES=4 -DBUILD_SHARED_LIBS=TRUE -DCMAKE_DISABLE_FIND_PACKAGE_LATEX=TRUE -DCMAKE_DISABLE_FIND_PACKAGE_Alberta=TRUE -DCMAKE_DISABLE_FIND_PACKAGE_Vc=TRUE -DCMAKE_DISABLE_DOCUMENTATION=TRUE"
    # cmake flags we use for all dune moudle - important is that build shared libs is set (need some better way of doing this)
    DUNECI_CMAKE_FLAGS: $DUNE_CMAKE_FLAGS
  tags: [duneci]
