---
include:
  - project: 'core/ci-config'
    ref: master
    file: 'config/common/master.yml'
  - project: 'core/ci-config'
    ref: master
    file: 'jobs/common/master.yml'

before_script:
  - . /duneci/bin/duneci-init-job
  - duneci-install-module https://gitlab.dune-project.org/core/dune-common.git
  - duneci-install-module https://gitlab.dune-project.org/core/dune-geometry.git
  - duneci-install-module https://gitlab.dune-project.org/staging/dune-uggrid.git

variables:
  # Alberta + python bindings fail at the moment with linker error
  DUNECI_CMAKE_FLAGS: "-DCMAKE_DISABLE_FIND_PACKAGE_Alberta=1"

debian-11-gcc-9-17-nobindings:
  <<: *common
  image: registry.dune-project.org/docker/ci/debian:11
  variables:
    DUNECI_TOOLCHAIN:  gcc-9-17
    DUNECI_CMAKE_FLAGS: "-DDUNE_ENABLE_PYTHONBINDINGS=0"

ubuntu-20.04-clang-10-20-nopython:
  <<: *common
  image: registry.dune-project.org/docker/ci/ubuntu:20.04
  variables:
    DUNECI_TOOLCHAIN: clang-10-20
    DUNECI_CMAKE_FLAGS: "-DCMAKE_DISABLE_FIND_PACKAGE_Python3=1"

# no numpy version available for this image on the gitlab registry
# disable python bindings for now
ubuntu:18.04 clang-6-17:
  <<: *common
  image: registry.dune-project.org/docker/ci/ubuntu:18.04
  variables:
    DUNECI_TOOLCHAIN: clang-6-17
    DUNECI_CMAKE_FLAGS: "-DDUNE_ENABLE_PYTHONBINDINGS=0"

ubuntu:18.04 clang-5-17:
  <<: *common
  image: registry.dune-project.org/docker/ci/ubuntu:18.04
  variables:
    DUNECI_TOOLCHAIN: clang-5-17
    DUNECI_CMAKE_FLAGS: "-DDUNE_ENABLE_PYTHONBINDINGS=0"
